<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-05-21 06:23
=======
# Generated by Django 2.2.1 on 2019-05-27 15:35
>>>>>>> bcde6757cd3e8f462d9e3530d628140754152c24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
